#!/bin/bash


if [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]; then
    echo "USAGE `basename $0` BRANCH"
    echo -e "\tBRANCH\tThe name to check out on the current repository and perfer on all the submodules."
    exit 1
fi

if [ $# -lt 1 ]; then
    branch="$(git branch --show-current)"
    echo "Using current branch '$branch'..."
else
    branch="$1"
    git checkout $branch
fi

git pull
git submodule foreach --recursive bash -c \
    'git checkout '"$branch"' || git checkout dev || git checkout main || git checkout master && git pull'
